export const labels = [
  "a-line",
  "abdomen",
  "accipitridae",
  "accipitriformes",
  "active pants",
  "active shirt",
  "active shorts",
  "active tank",
  "active undergarment",
  "advertising",
  "afro",
  "aluminium",
  "amphibians",
  "analog watch",
  "animal product",
  "animated cartoon",
  "animation",
  "ankle",
  "apron",
  "automotive tail & brake light",
  "aviator sunglasses",
  "baby & toddler clothing",
  "baby & toddler shoe",
  "baby products",
  "backpack",
  "badge",
  "bag",
  "baggage",
  "balance",
  "ball",
  "ballet flat",
  "bangle",
  "barechestedness",
  "baseball cap",
  "basic pump",
  "basketball",
  "basketball shoe",
  "bead",
  "beak",
  "beanie",
  "beard",
  "beauty",
  "belt",
  "belt buckle",
  "beret",
  "bermuda shorts",
  "bib",
  "bicycle clothing",
  "bicycle jersey",
  "bicycle shoe",
  "bikini",
  "bird",
  "black",
  "black hair",
  "blazer",
  "blue",
  "boardshorts",
  "boat",
  "boats and boating--equipment and supplies",
  "body jewelry",
  "bodybuilder",
  "bodybuilding",
  "bone",
  "boot",
  "bottle",
  "bottle cap",
  "bowtie",
  "box",
  "bra",
  "bracelet",
  "brass",
  "brassiere",
  "bridal shoe",
  "briefcase",
  "briefs",
  "bronze",
  "brown",
  "buckle",
  "business bag",
  "button",
  "calf",
  "camera",
  "camisole",
  "camouflage",
  "canidae",
  "cap",
  "carbon fibers",
  "cardboard packaging",
  "cardigan",
  "cargo pants",
  "carnivores",
  "cartoon",
  "case",
  "chain",
  "child",
  "chin",
  "chocolate",
  "choker",
  "christmas stocking",
  "circuit component",
  "cleat",
  "cloche hat",
  "clock",
  "clog",
  "clothes hanger",
  "clothing",
  "coat",
  "cocktail dress",
  "coin purse",
  "collar",
  "composite material",
  "copper",
  "cosmetics",
  "costume",
  "costume design",
  "costume hat",
  "court shoe",
  "cover-up",
  "cowboy boot",
  "craft",
  "cream",
  "creative arts",
  "cricket cap",
  "crochet",
  "crop top",
  "cross training shoe",
  "cuff",
  "cufflink",
  "cutting board",
  "cycling shoe",
  "cycling shorts",
  "cylinder",
  "dancing shoe",
  "day dress",
  "denim",
  "design",
  "dessert",
  "diamond",
  "diaper bag",
  "digital clock",
  "dinosaur",
  "dishcloth",
  "display device",
  "dog",
  "dog collar",
  "dog supply",
  "doll",
  "door handle",
  "dress",
  "dress shirt",
  "dress shoe",
  "duffel bag",
  "durango boot",
  "dye",
  "earring",
  "earrings",
  "elbow",
  "elbow pad",
  "electrical cable",
  "electrical connector",
  "electronic component",
  "electronic device",
  "electronics",
  "embellishment",
  "emblem",
  "embroidery",
  "engagement ring",
  "everyday carry",
  "exercise",
  "eyewear",
  "facial expression",
  "facial hair",
  "fashion",
  "fashion design",
  "fashion illustration",
  "fashion model",
  "fedora",
  "felidae",
  "fictional character",
  "finger food",
  "fish",
  "fisherman sandal",
  "flip-flops",
  "floral design",
  "fluid",
  "font",
  "food",
  "foot",
  "football",
  "footwear",
  "forehead",
  "formal wear",
  "fur",
  "fur clothing",
  "futebol de salão",
  "futsal",
  "gadget",
  "gemstone",
  "gesture",
  "gift",
  "glacial landform",
  "glass",
  "glass bottle",
  "glasses",
  "goggles",
  "gold",
  "gps case",
  "graphic design",
  "graphics",
  "green",
  "grey",
  "grommet",
  "hair care",
  "hair tie",
  "hand luggage",
  "handbag",
  "handle",
  "happiness",
  "hat",
  "headband",
  "headgear",
  "headpiece",
  "hero",
  "hide",
  "high heels",
  "high-heeled shoe",
  "high-visibility clothing",
  "hiking boot",
  "hiking equipment",
  "hiking shoe",
  "hip",
  "hobo bag",
  "home appliance",
  "hood",
  "hoodie",
  "household hardware",
  "household supply",
  "human back",
  "incontinence aid",
  "indoor soccer",
  "infant bodysuit",
  "jacket",
  "jaw",
  "jean shorts",
  "jeans",
  "jelly shoes",
  "jersey",
  "jewellery",
  "jewelry making",
  "jockstrap",
  "justice league",
  "khaki pants",
  "kitchen towel",
  "kitchen utensil",
  "knee",
  "knee pad",
  "knee-high boot",
  "knit cap",
  "knitting",
  "knot",
  "label",
  "landfowl",
  "laptop bag",
  "leash",
  "leather",
  "leather jacket",
  "led display",
  "leg",
  "leggings",
  "lid",
  "linen",
  "linens",
  "lingerie",
  "lingerie top",
  "liquid",
  "little black dress",
  "locket",
  "logo",
  "long hair",
  "long underwear",
  "long-sleeved t-shirt",
  "love",
  "luggage & bags",
  "machine",
  "mail bag",
  "makeover",
  "mannequin",
  "mario",
  "mary jane",
  "mat",
  "measuring instrument",
  "mesh",
  "messenger bag",
  "metal",
  "military camouflage",
  "military uniform",
  "mineral",
  "miniskirt",
  "model",
  "motif",
  "motorcycle boot",
  "moustache",
  "muscle",
  "napkin",
  "natural foods",
  "natural material",
  "natural rubber",
  "neck",
  "necklace",
  "necktie",
  "nickel",
  "nightgown",
  "nightwear",
  "nike free",
  "ninja",
  "number",
  "nurse uniform",
  "octopus",
  "office instrument",
  "office supplies",
  "one-piece garment",
  "onyx",
  "orange",
  "outdoor shoe",
  "outerwear",
  "overall",
  "overcoat",
  "oxford shoe",
  "pack animal",
  "packaging and labeling",
  "paisley",
  "pajamas",
  "pants",
  "pantyhose",
  "paper product",
  "parka",
  "passive circuit component",
  "pattern",
  "pencil case",
  "pencil skirt",
  "pendant",
  "perfume",
  "person",
  "personal care",
  "personal protective equipment",
  "pet supply",
  "photo shoot",
  "pink",
  "plaid",
  "plastic",
  "plastic bottle",
  "platinum",
  "plimsoll shoe",
  "plush",
  "pocket",
  "polar fleece",
  "polo shirt",
  "pre-engagement ring",
  "printing",
  "produce",
  "protective gear in sports",
  "puffer",
  "pumas",
  "puppy",
  "purple",
  "quartz clock",
  "rail transport",
  "rain boot",
  "rain pants",
  "rain suit",
  "raincoat",
  "red",
  "reptile",
  "ribbon",
  "riding boot",
  "ring",
  "rope",
  "rose",
  "rose family",
  "ruffle",
  "rug",
  "rugby ball",
  "rugby shorts",
  "running shoe",
  "sandal",
  "satchel",
  "satin",
  "scaled reptiles",
  "scarf",
  "school uniform",
  "science",
  "see-through clothing",
  "shark",
  "shawl",
  "sheath dress",
  "shirt",
  "shoe",
  "shopping bag",
  "shorts",
  "shoulder",
  "shoulder bag",
  "silk",
  "silver",
  "sink",
  "skate shoe",
  "skeleton",
  "skin care",
  "skirt",
  "skort",
  "skull",
  "sleeve",
  "sleeveless shirt",
  "slide sandal",
  "slingback",
  "slipper",
  "slope",
  "smile",
  "sneakers",
  "snow boot",
  "soccer ball",
  "soccer cleat",
  "soccer player",
  "soccer-specific stadium",
  "sock",
  "spandex",
  "sphere",
  "sponge",
  "sports",
  "sports bra",
  "sports equipment",
  "sports fan jersey",
  "sports toy",
  "sports uniform",
  "sportswear",
  "standing",
  "steel",
  "steel-toe boot",
  "still life",
  "still life photography",
  "stitch",
  "stocking",
  "stole",
  "stomach",
  "strap",
  "strapless dress",
  "suede",
  "suit trousers",
  "suitcase",
  "sun hat",
  "sunglasses",
  "superhero",
  "surfboard",
  "surfing--equipment and supplies",
  "sweater",
  "sweater vest",
  "sweatpants",
  "swim briefs",
  "swim cap",
  "swimmer",
  "swimsuit",
  "swimsuit bottom",
  "swimsuit top",
  "swimwear",
  "symbol",
  "synthetic rubber",
  "t-shirt",
  "tartan",
  "technology",
  "tennis shoe",
  "tennis skirt",
  "textile",
  "thermal bag",
  "thigh",
  "thorax",
  "tie",
  "tights",
  "tin",
  "titanium",
  "toe",
  "toiletry bag",
  "tool",
  "top",
  "torso",
  "tote bag",
  "towel",
  "toy",
  "toy dog",
  "track",
  "train",
  "train station",
  "transparency",
  "trench coat",
  "triangle",
  "trousers",
  "trucker hat",
  "trunks",
  "tube top",
  "turban",
  "tutu",
  "umbrella",
  "undergarment",
  "underpants",
  "undershirt",
  "uniform",
  "vacation",
  "vacuum flask",
  "velvet",
  "vest",
  "vintage clothing",
  "vision care",
  "visor",
  "waist",
  "walking shoe",
  "wallet",
  "watch",
  "water bottle",
  "water shoe",
  "webbing",
  "wedding ceremony supply",
  "wedge",
  "white",
  "white-collar worker",
  "windbreaker",
  "winter",
  "wire",
  "wool",
  "woolen",
  "work boots",
  "workwear",
  "wrap",
  "wrench",
  "wrestling shoe",
  "wristband",
  "wristlet",
  "yarn",
  "yellow",
  "yoga pants",
  "youth",
  "zipper"
];