export const mockProducts = {
    products: [
      {
        title: "Elegant Necklace",
        description: "A beautiful blue necklace.",
        color: "blue",
        material: "Gold-plated",
        size: "Adjustable",
        brand: "LuxuryJewels",
        rating: 4.8,
        price: "$25.99",
        link: "https://example.com/product1",
      },
      {
        title: "Stylish Bracelet",
        description: "A trendy bracelet in blue.",
        color: "blue",
        material: "Stainless Steel",
        size: "Medium",
        brand: "TrendyWear",
        rating: 4.5,
        price: "$19.99",
        link: "https://example.com/product2",
      },
      {
        title: "Classic Earrings",
        description: "Timeless earrings for any occasion.",
        color: "gold",
        material: "14K Gold",
        size: "One Size",
        brand: "GoldenCharm",
        rating: 4.7,
        price: "$15.49",
        link: "https://example.com/product3",
      },
      {
        title: "Bohemian Ring",
        description: "A stylish bohemian ring with intricate details.",
        color: "silver",
        material: "Sterling Silver",
        size: "7",
        brand: "BohoStyle",
        rating: 4.6,
        price: "$12.99",
        link: "https://example.com/product4",
      },
      {
        title: "Elegant Watch",
        description: "A sleek and modern watch for all occasions.",
        color: "black",
        material: "Leather",
        size: "Large",
        brand: "TimeMaster",
        rating: 4.9,
        price: "$49.99",
        link: "https://example.com/product5",
      },
    ],
  };